## Spring Boot actuator endpoints
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      group:
        custom:
          showComponents: always
          showDetails: always
  endpoints:
    web:
      exposure:
        include: '*'